version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app_Dockerfile
    tty: true
    ports: # ホストのポート:コンテナのポート
      - 9000:5000
    volumes:
      - ./src:/home/www
    depends_on:
      - rdb
  migrate:
    build:
      context: .
      dockerfile: django_Dockerfile
    tty: true
    environment:
      DB_HOST: rdb
      POSTGRES_DB: nim_sample
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      TZ: Asia/Tokyo
    volumes:
      - ./migrate:/home/www
    depends_on:
      - rdb
  rdb:
    image: postgres:alpine
    tty: true
    environment:
      POSTGRES_DB: nim_sample
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      # - .nim_data:/var/lib/postgresql/data
      - ./docker/rdb/initdb:/docker-entrypoint-initdb.d
