version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app_Dockerfile
    tty: true
    ports: # ホストのポート:コンテナのポート
      - 9000:5000
    volumes:
      - ./src:/home/www
      - ./docker/rdb/data:/home/db
    # depends_on:
    #   - rdb
  migrate:
    build:
      context: .
      dockerfile: python_Dockerfile
    tty: true
    volumes:
      - ./migrate:/home/www
      - ./docker/rdb/data:/home/db
  # rdb:
  #   image: postgres:alpine
  #   tty: true
  #   environment:
  #     POSTGRES_DB: nim_sample
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     TZ: Asia/Tokyo
  #   volumes:
  #     # - .nim_data:/var/lib/postgresql/data
  #     - ./docker/rdb/initdb:/docker-entrypoint-initdb.d
